spring:
  application:
    name: HotelBooking

  datasource:
    url: jdbc:mysql://localhost:4306/hotelbooking
    username: hotelbooking
    password: hotelbooking

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
